spring:
  security:
    panda:
      ignore-url:
        - /api/auth/oauth/token/**
        - /api/test/openApi/**
      strip-prefix: 2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: panda-business-test
          uri: lb://panda-business-test
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: panda-buiness-dbagent
          uri: lb://panda-business-dbagent
          predicates:
            - Path=/api/dbagent/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: panda-business-auth
          uri: lb://panda-business-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: panda-business-file
          uri: lb://panda-business-file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: panda-business-file
          uri: lb://panda-business-file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: panda-business-hello
          uri: lb://panda-business-hello
          predicates:
            - Path=/api/hello/**
          filters:
            - StripPrefix=${spring.security.panda.strip-prefix}
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar