spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ALGORTHIM_DATABASE
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true # 开启文件上传支持
      file-size-threshold: 0 # 文件写入磁盘的阀值
      location: D:\Sources\Files # 上传文件的临时保存位置
      max-request-size: 10MB # 多文件上传时文件的总大小
      max-file-size: 1MB # 上传的单个文件的最大大小
      resolve-lazily: false # 文件是否延迟解析
  resources:
    static-locations: file:${spring.servlet.multipart.location}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: sys_enable # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  gen:
    output-dir: ${project.path}\src\main\java
    mapper-xml: ${project.path}\src\main\resources\mapper
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    parent: com.daoren.file
  type-enums-package: com.daoren.*.enums