apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketdemo
  labels:
    app: rocketdemo
spec:
  serviceName: rocketdemo
  replicas: 1
  template:
    metadata:
      name: rocketdemo
      labels:
        app: rocketdemo
    spec:
      containers:
        - name: rocketdemo
          image: panda-business-rocketmq-boot-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: rocketdemo
---
apiVersion: v1
kind: Service
metadata:
  name: rocketdemo
spec:
  selector:
    app: rocketdemo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort